shared:
    image: node:8

jobs:
    main:
        annotations: 
            beta.screwdriver.cd/restrict-pr: fork
        requires:
            - ~pr
            - ~commit
        steps:
            - echo: echo test
