shared:
    image: node:8
annotations: 
    beta.screwdriver.cd/restrict-pr: fork
jobs:
    main:
        requires:
            - ~pr
            - ~commit
        steps:
            - echo: echo test
